POST http://localhost:3000/api/auth/register HTTP/1.1

{
	"email":"ggolfz",
	"password":"ggolfz",
	"firstname":"ggolfz",
	"lastname":"ggolfz"
}

POST http://localhost:3000/api/auth/login HTTP/1.1

{
	"email":"ggolfz",
	"password":"ggolfz"
}

GET http://localhost:3000/api/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.RMSl5t1Jvvl_m9oVcVszB5mgAzHhcsqetoMp-6hF-vw

PATCH http://localhost:3000/api/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.RMSl5t1Jvvl_m9oVcVszB5mgAzHhcsqetoMp-6hF-vw

{
	"email": "ggolfz",
	"firstname": "I'm Golf",
	"lastname": "ggolfz"
}

PATCH http://localhost:3000/api/user/password HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.RMSl5t1Jvvl_m9oVcVszB5mgAzHhcsqetoMp-6hF-vw

{
	"password": "ggolfz"
}

GET http://localhost:3000/api/medical HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.RMSl5t1Jvvl_m9oVcVszB5mgAzHhcsqetoMp-6hF-vw

PATCH http://localhost:3000/api/medical HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMH0.RMSl5t1Jvvl_m9oVcVszB5mgAzHhcsqetoMp-6hF-vw

{
	"gender": 1
}